# do not edit this file. put files in the dir below.
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$script_dir"

function await_user_action {
  set +x
  echo "$1"
  echo "hit enter to continue"
  read foo
  set -x
}

export -f await_user_action

for FN in "$script_dir"/osx/*.sh ; do
    "$FN"
done
