#!/bin/bash
set -uex -o pipefail

function .base {
    /usr/bin/git --git-dir="$HOME/.dotfiles/base" --work-tree="$HOME" "$@"
}

# initialize submodules
.base submodule init
.base submodule update

# install vim plugins
vim +PluginInstall +qall
